workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Plex-API:
        inputs:
            - location: pms-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/lukehagar/lukehagar/plex-api
targets: {}
