workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  Plex-API:
    inputs:
      - location: ./output/plex-media-server-spec-dereferenced.yaml
    registry:
      location: registry.speakeasyapi.dev/plexapi/plexapi/plex-api
targets: {}
