workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  plexapi:
    inputs:
      - location: ./src/pms-spec.yaml
    ruleset: PathParamRuleset
    registry:
      location: registry.speakeasyapi.dev/plexapi/plexapi/plexapi
targets: {}
