get:
  tags:
    - Plex.tv
  summary: Get User Opt Out Settings
  description: Get User Opt Out Settings
  operationId: getUserOptOutSettings
  responses:
    "200":
      description: User Opt Out Settings
      content:
        application/json:
          schema:
            type: object
            properties:
              tv.plex.provider.podcasts:
                type: string
                example: opt_in
              tv.plex.provider.news:
                type: string
                example: opt_in
              tv.plex.provider.webshows:
                type: string
                example: opt_out
              tv.plex.provider.music:
                type: string
                example: opt_out
              tv.plex.provider.vod:
                type: string
                example: opt_in
              scrobbling:
                type: string
                example: opt_in

    "400":
      $ref: "../../responses/400.yaml"
    "401":
      $ref: "../../responses/401.yaml"
