name: Build and Copy Dereferenced Plex TV API Spec

on:
  push:
    branches:
      - main
    paths:
      - plextv/**
  workflow_dispatch:

jobs:
  dereference_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Dereference Plex TV Specification
        run: |
          swagger-cli bundle --dereference plextv/plextv-spec.yaml -t yaml -o plex-tv-spec-dereferenced.yaml

      # - name: Pushes Dereferenced Specification File
      #   uses: dmnemec/copy_file_to_another_repo_action@main
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      #   with:
      #     source_file: plex-tv-spec-dereferenced.yaml
      #     destination_repo: lukehagar/plex-docs
      #     destination_folder: static
      #     user_email: lukeslakemail@gmail.com
      #     user_name: lukehagar
      #     commit_message: Updating PlexTV Spec

      - uses: stefanzweifel/git-auto-commit-action@v4
