name: Build and Copy Dereferenced Plex Media Server API Spec

on:
  push:
    branches:
      - main
    paths:
      - src/**

  workflow_dispatch:

jobs:
  dereference_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Dereference Plex Media Server Specification
        run: bun run build

      - name: Commit Dereferenced Specification File
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: dereferenced Plex Media Server API Spec updated"

      - name: Pushes Dereferenced Specification File
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: ./output/plex-media-server-spec-dereferenced.yaml
          destination_repo: lukehagar/plex-docs
          destination_folder: static
          user_email: lukeslakemail@gmail.com
          user_name: lukehagar
          commit_message: Updating PMS Spec

