name: Build and Copy Dereferenced Plex Media Server API Spec

on:
  push:
    branches:
      - main
    paths:
      - src/**

  workflow_dispatch:

jobs:
  dereference_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Project Setup
        uses: ./.github/workflows/steps/project-setup

      - name: Dereference Plex Media Server Specification
        run: bun run build

      - name: Commit Dereferenced Specification File
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: dereferenced Plex Media Server API Spec updated"
          skip_checkout: true
          skip_fetch: true
          add_options: "-f"
          file_pattern: "./output/*.yaml"
          skip_dirty_check: true