name: "Build Dereferenced Plex API Spec"

on:
  push:
    branches:
      - main
    paths:
      - referenced/**
  workflow_dispatch:

jobs:
  dereference_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli
      - name: Dereference Plex API Specification
        run: |
          swagger-cli bundle --dereference referenced/plex-api-spec.yaml -t yaml -o plex-api-spec-dereferenced.yaml
      - name: Commit and push changes
        run: |
          git config --global user.name "LukeHagar"
          git config --global user.email "Lukeslakemail@gmail.com"

          git add -A
          git commit -m "Automated Commit: Dereferencing Plex API Specification"
          git push
