name: Linting
"on":
  pull_request:
    paths:
      - src/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Install Speakeasy CLI
        run: bun run setup-speakeasy-cli

      - name: OpenAPI Lint
        run: bun run lint
