name: Unit Tests
"on":
  pull_request:
    paths:
      - src/**
      - tests/**

jobs:
  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Project Setup
        uses: ./.github/workflows/steps/project-setup

      - name: Bundle OpenAPI Spec
        run: bun run build

      - name: Run Unit Tests
        run: bun run test

  type-check:
    name: Run Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Project Setup
        uses: ./.github/workflows/steps/project-setup

      - name: Run Unit Tests
        run: bun run type-check
