name: Linting
"on":
  pull_request:
    paths:
      - src/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Install Speakeasy CLI
        run: bun run setup-speakeasy-cli

#      TODO: Disable this step until the linting is fixed in speakeasy with regards to $ref parameters in the OpenAPI spec `GET` must define parameter `ratingKey` as expected by path `/library/metadata/{ratingKey}`
#      - name: OpenAPI Lint
#        run: bun run lint

      - name: Bundle OpenAPI Spec
        run: bun run build

      - name: OpenAPI Lint On Bundled Spec
        run: bun run lint-bundled
