name: Unit Tests
"on":
  pull_request:
    paths:
      - src/**
      - tests/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Bundle OpenAPI Spec
        run: bun run build

      - name: Run Unit Tests
        run: bun run test
